theme: jekyll-theme-slate
title: MeshRIR
description: Dataset of room impulse responses on meshed grid points
show_downloads: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
google_analytics: G-QK7GTK0C8N
logo: img/logo.png
lang: en
